TAGS = [
  'Adoption',
  'Alimentation',
  'Anorexie',
  'Boule de poil',
  'Chat âgé',
  'Chaton',
  'Chien âgé',
  'Chiot',
  'Cohabitation',
  'Croquette',
  'Digestion',
  'Dressage',
  'Education',
  'Herbe à chat',
  'Hygiène',
  'Litière',
  'Loisir',
  'Maladie',
  'Pâtée',
  'Premier chat',
  'Premier chien',
  'Propreté',
  'Reproduction',
  'Sevrage',
  'Sexe',
  'Socialisation',
  'Sport canin',
  'Stérilisation',
  'Surpoids',
  'Transport',
  'Vaccination',
  'Vétérinaire',
  'Voyage'
]
